### ISSUE TITLE
Add note that the SIM tray slots are labeled the wrong way around

### ISSUE THREAD

**Issue by ZimbiX** [shymega/planet-devices-wiki-prs#28]
From [this post on OESF](https://www.oesf.org/forum/index.php?topic=36938.msg299492#msg299492)

**Comment by shymega** [comment]
Wondering how to structure this in the wiki. Maybe a 'Astro Tips and Tricks' section?

**Comment by ZimbiX** [comment]
Yeah, that could work. Unless we'd have enough content for a 'Astro Cellular' page or similar - maybe also detailing what we know about the modem crashing and dropouts?

Edit: Actually, that's probably sufficiently covered by the issue

Edit 2: This could be an issue as well, but being an unfixable thing, I guess an unclosable issue is undersirable

**Comment by shymega** [comment]
Honestly, I think it's best to make an 'Astro Cellular' page. We could then ask the community to document what providers work with which baseband, etc. A table with network provider (for MVNOs, the backbone network), baseband version, and network data type: 5G/4G/3G. What do you think?
