### ISSUE TITLE
Add rooted boot image for V07b

### ISSUE THREAD

**Issue by ZimbiX** [shymega/planet-devices-wiki-prs#39]
I haven't risked upgrading from V07 yet, so haven't been able to add it to [the list in the wiki](https://github.com/shymega/planet-devices/wiki/Astro-rooting#rooting-method-1-use-a-pre-patched-boot-image). I'll get around to it at some point; or someone else can feel free to do it.

**Comment by shymega** [comment]
Just done this. Someone mentioned on the Discord as well.

I've renamed `boot-v01-magisk-from-app.img` to `boot-v01-magisk-from-app-26300.img` to be in line with the other filenames.

I've also added stock boot-v07b and rooted that image on my Astro (Magisk 26.3).

Made a PR, and will merge shortly. The `planet-devices` repo also has the new boot images pushed.

**Comment by shymega** [comment]
Done.

**Comment by ZimbiX** [comment]
Thanks for that. I noticed a couple of mistakes, so fixed those in https://github.com/shymega/planet-devices-wiki-prs/pull/41.

Are your V07b images definitely right? I see they have the same checksums as V07. If so, I'm fine with leaving the files duplicated, but it could be worth explicitly stating it's unchanged from V07 (i.e. that it's not a mistake).

**Comment by ZimbiX** [comment]
Also, I'm not sure that it's worth the effort to go back and update the older magisk'd images. (Are people really going to be rooting the device without applying the latest OTA?) Otherwise the release of each OTA produces an increasing amount of update work when a new Magisk version comes out, to re-Magisk all the images. Although both OTA and Magisk updates do seem to be rare events.

**Comment by shymega** [comment]
> Thanks for that. I noticed a couple of mistakes, so fixed those in #41.
> 
> Are your V07b images definitely right? I see they have the same checksums as V07. If so, I'm fine with leaving the files duplicated, but it could be worth explicitly stating it's unchanged from V07 (i.e. that it's not a mistake).

Yes, they were readback from my Astro, running V07b. A note might be necessary, yes.

Thanks for the PR, too

**Comment by shymega** [comment]
> Also, I'm not sure that it's worth the effort to go back and update the older magisk'd images. (Are people really going to be rooting the device without applying the latest OTA?) Otherwise the release of each OTA produces an increasing amount of update work when a new Magisk version comes out, to re-Magisk all the images. Although both OTA and Magisk updates do seem to be rare events.

I don't think it's too much of an issue. It's a one-off in this case, and as I updated to the latest stock image, it made sense to bump the Magisk patch. They are not as often as they could be [OTA+Magisk], so it's very little effort to maintain.

**Comment by ZimbiX** [comment]
Correct boot images for V07b have finally been added in https://github.com/shymega/planet-devices-wiki-prs/pull/43.

**Comment by shymega** [comment]
Thanks for this. Examining now. It turns out, `mtkclient r boot` just reads from... well, it must be using a different partition. I know that `fastboot` aliases `boot` to *either* `boot_a` or `boot_b` - so I'm a little confused. I wonder if my scatter file for the Astro will shed any light.
